<?php

class Resources {

	public static function HomeName() {
		echo "Home";
	}

	public static function ServiceName() {
		echo "Services";
	}

	public static function CompanyName() {
		echo "Company";
	}

	public static function BlogName() {
		echo "Blog";
	}

	public static function ContactName() {
		echo "Contact Us";
	}

	public static function CopyRight() {
		echo "© 2013-2014 CMMS Software. All Rights Reserved";
	}

	public static function CompanyMainDescription() {
		echo "We are a family company, a place where make software! Let me know your needs and we build your solution!";
	}

	public static function ServicesMainDescription() {
		echo "We have experience and knowledge on several technologies and environments, developing applications for web, desktop and mobile platforms.";
	}
	
	public static function ServicesSubDescription(){
		echo "{ Architecture - Software Development - Consultancy }";
	}
	
	public static function EmailTooltip() {
		echo "Send us an email!";
	}

	public static function TwitterTooltip() {
		echo "Visit us page!";
	}

	public static function FacebookTooltip() {
		echo "Visit us page!";
	}
	
	public static function ComingSoon() {
		echo "Coming Soon! :)";
	}
	

}
?>